name: P5-medical-migration
services:
  mongo:
    image: mongo:7.0.14
    container_name: mongodb-medical
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
      MONGO_INITDB_DATABASE: medical_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-db:/docker-entrypoint-initdb.d
    command: --auth --quiet --logpath /dev/null

  migration:
    build: .
    container_name: medical-migration
    env_file:
      - .env                          # ← charge le .env 
    volumes:
      - .:/app                        # pour voir les logs sur ton PC
    working_dir: /app
    depends_on:
      - mongo
    # Charge MongoDB
    command: >
      sh -c "
        echo 'Attente de MongoDB...' &&
        until python -c 'from pymongo import MongoClient; MongoClient(\"mongo:27017\", serverSelectionTimeoutMS=2000).admin.command(\"ping\")' 2>/dev/null; do
          sleep 2
        done &&
        echo 'MongoDB prêt ! Lancement de la migration...' &&
        python main.py
      "

volumes:
  mongo-data: