version: '3.9'

services:
  mongo:
    image: mongo:7.0.14
    container_name: mongodb-medical
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin1234
      MONGO_INITDB_DATABASE: medical_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./init-db:/docker-entrypoint-initdb.d   # pour créer les users + rôles automatiquement
    command: --auth

volumes:
  mongo-data: